import { useEffect, useMemo, useState, type FormEvent, type ReactNode } from "react";
import { Bell, BookOpen, CheckCircle2, ChevronRight, ClipboardList, Eye, EyeOff, FileText, GraduationCap, LayoutDashboard, LockKeyhole, LogOut, Menu, Search, ShieldCheck, Upload, UserRound, Users, X } from "lucide-react";
import { addEvent, addProgram, deactivateProgram, getEnrollments, getPrograms, isSupabaseConfigured, registerFreshman, requestAccess, resetPassword, restoreProfile, roleLabel, saveEnrollment, signIn, signOut, stateLabel, supabase, uploadDocument, type Enrollment, type Office, type Profile, type Role, type StudentForm } from "./lib/system";

const roles: Role[] = ["registrar", "osas", "guidance", "medical", "scholarship", "cashier", "ict", "admin"];
const steps = ["Student information", "Registrar requirements", "Assessment & insurance", "Support clearances", "School ID", "Final review"];
const requirements: Record<string, string[]> = {
  freshman: ["Senior High School Report Card", "Certificate of Good Moral Character", "PSA Birth Certificate", "2 × 2 ID picture", "Student Information Sheet"],
  transferee: ["Transfer Credential", "Transcript of Records", "Certificate of Good Moral Character", "PSA Birth Certificate", "Student Information Sheet"],
  continuing: ["Accomplished Clearance Form", "Previous Enrollment Form", "Loading Slip (if irregular)"],
  returning: ["Accomplished Clearance Form", "Previous Enrollment Form", "Registrar re-admission approval"],
};
const sampleSubjects = [
  { code: "CS 101", title: "Introduction to Computing", units: 3, schedule: "MWF 7:30–8:30 AM", room: "CCS-101" },
  { code: "CS 102", title: "Programming Fundamentals", units: 3, schedule: "TTh 9:00–10:30 AM", room: "CCS-Lab 1" },
  { code: "MATH 101", title: "Mathematics in the Modern World", units: 3, schedule: "MWF 10:30–11:30 AM", room: "AS-201" },
  { code: "ENG 101", title: "Purposive Communication", units: 3, schedule: "TTh 1:00–2:30 PM", room: "AS-102" },
];

export default function App() {
  const [profile, setProfile] = useState<Profile | null>(null);
  const [loading, setLoading] = useState(true);
  useEffect(() => { restoreProfile().then(setProfile).finally(() => setLoading(false)); }, []);
  if (loading) return <Centered><div className="spinner"/><p>Loading enrollment portal…</p></Centered>;
  if (!profile) return <Auth onAuthenticated={setProfile}/>;
  return <Portal profile={profile} onExit={async () => { await signOut(); setProfile(null); }}/>;
}

function Auth({ onAuthenticated }: { onAuthenticated: (profile: Profile) => void }) {
  const [mode, setMode] = useState<"signin" | "freshman" | "access">("signin");
  const [form, setForm] = useState({ firstName: "", lastName: "", email: isSupabaseConfigured ? "" : "student@demo.chmsu.edu.ph", password: isSupabaseConfigured ? "" : "Student123!", confirmPassword: "", message: "", consent: false });
  const [showPassword, setShowPassword] = useState(false); const [showConfirmPassword, setShowConfirmPassword] = useState(false);
  const [busy, setBusy] = useState(false); const [notice, setNotice] = useState(""); const [error, setError] = useState("");
  const submit = async (event: FormEvent) => {
    event.preventDefault(); setBusy(true); setError(""); setNotice("");
    try {
      if (mode === "signin") onAuthenticated(await signIn(form.email, form.password));
      else if (mode === "freshman") {
        if (!form.firstName.trim() || !form.lastName.trim()) throw new Error("Enter your first and last name.");
        if (form.password.length < 8) throw new Error("Use at least 8 characters for your password.");
        if (form.password !== form.confirmPassword) throw new Error("Passwords do not match.");
        if (!form.consent) throw new Error("Confirm that your information is accurate to continue.");
        const result = await registerFreshman(form.firstName, form.lastName, form.email, form.password);
        if (result.status === "confirmation_required") {
          setMode("signin");
          setForm(previous => ({ ...previous, email: result.email, password: "", confirmPassword: "", consent: false }));
          setNotice("Account created. Check your email to confirm your account, then sign in.");
        } else onAuthenticated(result.profile);
      }
      else { await requestAccess(form.email, form.message); setNotice("Your access request was sent to the Registrar."); }
    } catch (reason) { setError(reason instanceof Error ? reason.message : "Something went wrong."); }
    finally { setBusy(false); }
  };
  const chooseDemo = (role: Role) => setForm({ ...form, email: `${role}@demo.chmsu.edu.ph`, password: "Staff123!" });
  const switchMode = (next: "signin" | "freshman" | "access") => { setMode(next); setError(""); setNotice(""); setShowPassword(false); setShowConfirmPassword(false); };
  const registration = mode === "freshman";
  return <div className="auth-page">
    <section className="auth-story"><div className="brand-mark"><GraduationCap size={30}/></div><p className="eyebrow">Carlos Hilado Memorial State University</p><h1>Your enrollment,<br/>clear from start to finish.</h1><p>Submit requirements, follow every approval, and receive your official enrollment form in one secure place.</p><div className="feature-list"><span><CheckCircle2/> Saved progress</span><span><ShieldCheck/> Role-protected records</span><span><Bell/> Live status updates</span></div></section>
    <main className="auth-panel"><div className="mobile-brand"><GraduationCap/> CHMSU Enrollment</div><div className={`auth-card ${registration ? "registration-card" : ""}`}><div className="auth-heading"><p className="eyebrow">AY 2026–2027 · 2nd Semester</p><h2>{mode === "signin" ? "Welcome back" : mode === "freshman" ? "Create your freshman account" : "Request account access"}</h2><p className="muted">{mode === "signin" ? "Sign in with your student or staff account." : mode === "freshman" ? "Set up your secure portal account to begin enrollment." : "Tell the Registrar which email should receive access."}</p></div>
      <form onSubmit={submit} className="stack">{registration && <div className="registration-fields"><div className="name-grid"><Field label="First name"><input required autoComplete="given-name" value={form.firstName} onChange={e => setForm({ ...form, firstName: e.target.value })}/></Field><Field label="Last name"><input required autoComplete="family-name" value={form.lastName} onChange={e => setForm({ ...form, lastName: e.target.value })}/></Field></div><div className="registration-note"><LockKeyhole/><span>Your account will be used to save your enrollment progress.</span></div></div>}<Field label="Email address"><input required autoComplete="email" type="email" value={form.email} onChange={e => setForm({ ...form, email: e.target.value })}/></Field>{mode !== "access" && <Field label="Password"><div className="password-control"><input required minLength={8} autoComplete={registration ? "new-password" : "current-password"} type={showPassword ? "text" : "password"} value={form.password} onChange={e => setForm({ ...form, password: e.target.value })}/><button type="button" className="password-toggle" aria-label={showPassword ? "Hide password" : "Show password"} onClick={() => setShowPassword(value => !value)}>{showPassword ? <EyeOff/> : <Eye/>}</button></div>{registration && <span className="field-hint">Use at least 8 characters. A mix of letters and numbers is recommended.</span>}</Field>}{registration && <Field label="Confirm password"><div className="password-control"><input required minLength={8} autoComplete="new-password" type={showConfirmPassword ? "text" : "password"} value={form.confirmPassword} onChange={e => setForm({ ...form, confirmPassword: e.target.value })}/><button type="button" className="password-toggle" aria-label={showConfirmPassword ? "Hide confirm password" : "Show confirm password"} onClick={() => setShowConfirmPassword(value => !value)}>{showConfirmPassword ? <EyeOff/> : <Eye/>}</button></div>{form.confirmPassword && form.password !== form.confirmPassword && <span className="field-error">Passwords do not match yet.</span>}</Field>}{mode === "access" && <Field label="Reason"><textarea required value={form.message} onChange={e => setForm({ ...form, message: e.target.value })}/></Field>}{registration && <label className="consent-row"><input type="checkbox" checked={form.consent} onChange={e => setForm({ ...form, consent: e.target.checked })}/><span>I confirm that the information I provide is accurate and may be used for enrollment processing.</span></label>}{error && <Alert tone="error">{error}</Alert>}{notice && <Alert tone="success">{notice}</Alert>}<button className="primary" disabled={busy}>{busy ? "Creating your account…" : mode === "signin" ? "Sign in" : mode === "freshman" ? "Create account" : "Send request"}</button></form>
      {mode === "signin" && <button className="link" onClick={async () => { await resetPassword(form.email); setNotice("If the account exists, a recovery email has been sent."); }}>Forgot password?</button>}<div className="auth-switches"><button onClick={() => switchMode(mode === "freshman" ? "signin" : "freshman")}>{mode === "freshman" ? "Already have an account? Sign in" : "New student? Start enrollment"}</button>{mode !== "freshman" && <button onClick={() => switchMode(mode === "access" ? "signin" : "access")}>{mode === "access" ? "Return to sign in" : "Request account access"}</button>}</div>
      {!isSupabaseConfigured && <details className="demo-box"><summary>Demo accounts</summary><p>Student: student@demo.chmsu.edu.ph / Student123!</p><div className="demo-roles">{roles.map(role => <button key={role} onClick={() => chooseDemo(role)}>{roleLabel(role)}</button>)}</div></details>}</div></main>
  </div>;
}

function Portal({ profile, onExit }: { profile: Profile; onExit: () => void }) {
  const [items, setItems] = useState<Enrollment[]>([]); const [loading, setLoading] = useState(true); const [mobile, setMobile] = useState(false);
  const reload = () => getEnrollments(profile).then(setItems).finally(() => setLoading(false));
  useEffect(() => { void reload(); }, [profile.id]);
  useEffect(() => {
    const client = supabase;
    if (!client) return;
    const channel = client.channel(`enrollments:${profile.id}`).on("postgres_changes", { event: "*", schema: "public", table: "enrollments" }, () => { void reload(); }).subscribe();
    return () => { void client.removeChannel(channel); };
  }, [profile.id]);
  const persist = async (item: Enrollment, action = "save") => { await saveEnrollment(item, action); await reload(); };
  return <div className="app-shell"><aside className={mobile ? "sidebar open" : "sidebar"}><div className="logo"><div className="brand-mark small"><GraduationCap/></div><div><strong>CHMSU</strong><span>Enrollment Hub</span></div><button className="icon mobile-only" onClick={() => setMobile(false)}><X/></button></div><div className="term-card"><span>Enrollment period</span><strong>AY 2026–2027</strong><small>2nd Semester · Open</small></div><nav>{profile.role === "student" ? <><Nav icon={<LayoutDashboard/>} label="My enrollment"/><Nav icon={<FileText/>} label="Documents"/><Nav icon={<Bell/>} label="Updates"/></> : <><Nav icon={<Users/>} label="Processing queue"/><Nav icon={<ClipboardList/>} label="Activity history"/>{profile.role === "admin" && <Nav icon={<BookOpen/>} label="Academic setup"/>}</>}</nav><div className="user-card"><div className="avatar">{profile.fullName[0]}</div><div><strong>{profile.fullName}</strong><span>{roleLabel(profile.role)}</span></div><button title="Sign out" className="icon" onClick={onExit}><LogOut/></button></div></aside>
    <div className="main-column"><header className="topbar"><button className="icon mobile-only" onClick={() => setMobile(true)}><Menu/></button><div><p className="eyebrow">CHMSU ONLINE SERVICES</p><strong>{profile.role === "student" ? "Student enrollment" : `${roleLabel(profile.role)} workspace`}</strong></div><span className={`connection ${isSupabaseConfigured ? "live" : "demo"}`}>{isSupabaseConfigured ? "Supabase connected" : "Local demo mode"}</span></header><main className="content">{loading ? <Centered><div className="spinner"/></Centered> : profile.role === "student" ? <StudentPortal item={items[0]} persist={persist}/> : profile.role === "admin" ? <AdminPortal items={items}/> : <StaffPortal profile={profile} items={items} persist={persist}/>}</main></div></div>;
}

function StudentPortal({ item, persist }: { item?: Enrollment; persist: (item: Enrollment, action?: string) => Promise<void> }) {
  const [working, setWorking] = useState(item); const [tab, setTab] = useState<"overview" | "enroll" | "documents" | "updates">("overview"); const [notice, setNotice] = useState("");
  useEffect(() => setWorking(item), [item]);
  if (!working) return <Empty title="No enrollment record" text="Create a freshman enrollment from the sign-in page or ask the Registrar to open a record."/>;
  const save = async (next = working, action = "save", message = "Draft saved.") => { setWorking(next); await persist(next, action); setNotice(message); };
  const progress = working.status === "confirmed" ? 100 : Math.round(((working.step - 1) / steps.length) * 100);
  return <><div className="page-head"><div><p className="eyebrow">Hello, {working.form.fullName || "Student"}</p><h1>{working.status === "confirmed" ? "You are officially enrolled" : "Complete your enrollment"}</h1><p>Follow each requirement and watch approvals update here.</p></div><Status value={working.status}/></div><div className="tabs"><button className={tab === "overview" ? "active" : ""} onClick={() => setTab("overview")}>Overview</button><button className={tab === "enroll" ? "active" : ""} onClick={() => setTab("enroll")}>Enrollment steps</button><button className={tab === "documents" ? "active" : ""} onClick={() => setTab("documents")}>Documents</button><button className={tab === "updates" ? "active" : ""} onClick={() => setTab("updates")}>Updates</button></div>{notice && <Alert tone="success">{notice}</Alert>}{tab === "overview" && <Overview item={working} progress={progress} onContinue={() => setTab("enroll")}/>} {tab === "enroll" && <EnrollmentWizard item={working} setItem={setWorking} save={save}/>} {tab === "documents" && <Documents item={working}/>} {tab === "updates" && <Timeline events={working.events}/>}</>;
}

function Overview({ item, progress, onContinue }: { item: Enrollment; progress: number; onContinue: () => void }) {
  const cleared = Object.values(item.offices).filter(value => value === "cleared").length;
  return <div className="overview-grid"><section className="hero-card"><p className="eyebrow">CURRENT PROGRESS</p><div className="hero-stat"><strong>{progress}%</strong><span>Step {item.step} of {steps.length}</span></div><div className="progress"><i style={{ width: `${progress}%` }}/></div><h2>{steps[item.step - 1]}</h2><p>Your draft is saved. Continue where you left off.</p><button className="primary" onClick={onContinue}>Continue enrollment <ChevronRight/></button></section><section className="card"><h3>At a glance</h3><div className="stats"><Stat value={`${cleared}/7`} label="Office clearances"/><Stat value={stateLabel(item.payment.status)} label="Insurance payment"/><Stat value={stateLabel(item.idStatus)} label="School ID"/><Stat value={item.studentNumber ?? "Not yet assigned"} label="Student number"/></div></section><section className="card wide"><h3>Latest activity</h3><Timeline events={item.events.slice(0, 4)}/></section></div>;
}

function EnrollmentWizard({ item, setItem, save }: { item: Enrollment; setItem: (item: Enrollment) => void; save: (item?: Enrollment, action?: string, message?: string) => Promise<void> }) {
  const [busy, setBusy] = useState(false); const updateForm = (key: keyof StudentForm, value: string) => setItem({ ...item, form: { ...item.form, [key]: value } });
  const next = async () => { if (item.step === 1 && !item.form.fullName.trim()) return alert("Full name is required."); const updated = addEvent({ ...item, step: Math.min(6, item.step + 1), status: item.status === "draft" ? "submitted" : item.status }, `${steps[item.step - 1]} submitted`); await save(updated, item.step === 1 ? "submit" : "save", "Step submitted successfully."); };
  const upload = async (office: string, key: string, file?: File) => { if (!file) return; setBusy(true); try { const path = await uploadDocument(item.id, office, file); const next = { ...item, documents: { ...item.documents, [key]: path }, payment: office === "cashier" ? { ...item.payment, proof: path, status: "submitted" as const } : item.payment }; await save(next, "save", `${file.name} uploaded.`); } finally { setBusy(false); } };
  return <div className="wizard"><div className="stepper">{steps.map((name, index) => <button key={name} className={item.step === index + 1 ? "active" : item.step > index + 1 ? "done" : ""} onClick={() => index + 1 <= item.step && setItem({ ...item, step: index + 1 })}><span>{item.step > index + 1 ? "✓" : index + 1}</span><small>{name}</small></button>)}</div><section className="card form-card"><div className="section-title"><div><p className="eyebrow">STEP {item.step} OF 6</p><h2>{steps[item.step - 1]}</h2></div><Status value={item.status}/></div>{item.step === 1 && <StudentInfo form={item.form} update={updateForm}/>} {item.step === 2 && <RequirementUpload item={item} upload={upload} busy={busy}/>} {item.step === 3 && <Payment item={item} upload={upload} busy={busy}/>} {item.step === 4 && <OfficeClearances item={item}/>} {item.step === 5 && <IdProcessing item={item}/>} {item.step === 6 && <FinalReview item={item}/>}<div className="form-actions"><button className="secondary" disabled={item.step === 1} onClick={() => setItem({ ...item, step: item.step - 1 })}>Back</button><button className="secondary" onClick={() => save()}>Save draft</button>{item.step < 6 && <button className="primary" onClick={next}>Save and continue <ChevronRight/></button>}</div></section></div>;
}

function StudentInfo({ form, update }: { form: StudentForm; update: (key: keyof StudentForm, value: string) => void }) {
  const fields: Array<[keyof StudentForm, string, string]> = [["fullName","Full name","text"],["birthDate","Date of birth","date"],["gender","Gender","text"],["mobile","Mobile number","tel"],["email","Email address","email"],["address","Home address","text"],["guardian","Parent or guardian","text"],["emergencyContact","Emergency contact","tel"]];
  return <div className="form-grid"><Field label="Student type"><select value={form.studentType} onChange={e => update("studentType", e.target.value)}>{["freshman","transferee","continuing","returning"].map(v => <option key={v} value={v}>{stateLabel(v)}</option>)}</select></Field><Field label="Academic status"><select value={form.academicStatus} onChange={e => update("academicStatus", e.target.value)}><option value="regular">Regular</option><option value="irregular">Irregular</option></select></Field><Field label="Campus"><select value={form.campus} onChange={e => update("campus", e.target.value)}>{["Talisay","Alijis","Fortune Towne","Binalbagan"].map(v => <option key={v}>{v}</option>)}</select></Field><Field label="Program"><select value={form.program} onChange={e => update("program", e.target.value)}>{["BS Computer Science","BS Information Technology","BS Business Administration","BS Criminology","Bachelor of Secondary Education"].map(v => <option key={v}>{v}</option>)}</select></Field>{fields.map(([key,label,type]) => <Field key={key} label={label}><input required={key === "fullName"} type={type} value={form[key]} onChange={e => update(key, e.target.value)}/></Field>)}</div>;
}

function RequirementUpload({ item, upload, busy }: { item: Enrollment; upload: (office: string, key: string, file?: File) => void; busy: boolean }) { return <div className="upload-list">{requirements[item.form.studentType].map((name, index) => <label className="upload-row" key={name}><div className="file-icon"><FileText/></div><div><strong>{name}</strong><span>{index > 2 ? "Bring original; digital copy optional" : "PDF, JPG or PNG · max 10 MB"}</span></div><Status value={item.documents[name] ? "uploaded" : "pending"}/><input disabled={busy} type="file" accept=".pdf,.jpg,.jpeg,.png" onChange={e => upload("registrar", name, e.target.files?.[0])}/><Upload/></label>)}</div>; }
function Payment({ item, upload, busy }: { item: Enrollment; upload: (office: string, key: string, file?: File) => void; busy: boolean }) { return <div className="payment-grid"><div className="invoice"><p>Free Higher Education / UniFAST</p><h3>Government-funded tuition</h3><div><span>Tuition payable</span><strong>₱0.00</strong></div><div><span>Student insurance</span><strong>₱125.00</strong></div><div className="total"><span>Total payable</span><strong>₱125.00</strong></div></div><div className="card inset"><Status value={item.payment.status}/><h3>Payment proof</h3><p>Pay through the designated Cashier channel, then upload a clear receipt or transaction image.</p><label className="dropzone"><Upload/><strong>{item.payment.proof || "Choose payment proof"}</strong><span>PDF, JPG or PNG · max 10 MB</span><input disabled={busy} type="file" accept=".pdf,.jpg,.jpeg,.png" onChange={e => upload("cashier", "payment-proof", e.target.files?.[0])}/></label>{item.payment.receipt && <Alert tone="success">Receipt issued: {item.payment.receipt}</Alert>}</div></div>; }
function OfficeClearances({ item }: { item: Enrollment }) { return <div className="office-grid">{(["osas","guidance","medical"] as Office[]).map(office => <div className="office-card" key={office}><div className="file-icon"><ShieldCheck/></div><div><h3>{roleLabel(office)}</h3><p>{item.remarks[office] || "No staff remarks."}</p></div><Status value={item.offices[office]}/></div>)}</div>; }
function IdProcessing({ item }: { item: Enrollment }) { return <div className="process"><div className="process-icon"><UserRound/></div><h3>{stateLabel(item.idStatus)}</h3><p>ICT-MIS verifies identity, captures the photo, assigns the student number, and prepares the school ID.</p>{item.studentNumber && <Alert tone="success">Assigned student number: {item.studentNumber}</Alert>}</div>; }
function FinalReview({ item }: { item: Enrollment }) { const checks = [["Student information",item.status !== "draft"],["Registrar requirements",item.offices.registrar === "cleared"],["Free Higher Education assessment",item.offices.scholarship === "cleared"],["Insurance payment",item.payment.status === "confirmed"],["OSAS clearance",item.offices.osas === "cleared"],["Guidance clearance",item.offices.guidance === "cleared"],["Medical clearance",item.offices.medical === "cleared"],["School ID processing",["ready","completed"].includes(item.idStatus)]] as const; return <div><div className="check-list">{checks.map(([name,done]) => <div key={name}><span className={done ? "check yes" : "check"}>{done ? "✓" : "!"}</span><strong>{name}</strong><Status value={done ? "verified" : "pending"}/></div>)}</div>{item.status === "confirmed" && <Confirmed item={item}/>}</div>; }
function Confirmed({ item }: { item: Enrollment }) { return <div className="confirmed"><CheckCircle2/><h2>Enrollment confirmed</h2><p>Student no. {item.studentNumber}</p><button className="primary" onClick={() => window.print()}>Print / Save as PDF</button><div className="subject-table">{item.subjects.map(subject => <div key={subject.code}><strong>{subject.code}</strong><span>{subject.title}</span><span>{subject.schedule}</span><span>{subject.room}</span></div>)}</div></div>; }

function StaffPortal({ profile, items, persist }: { profile: Profile; items: Enrollment[]; persist: (item: Enrollment, action?: string) => Promise<void> }) {
  const [query, setQuery] = useState(""); const [status, setStatus] = useState(""); const [selected, setSelected] = useState<Enrollment | null>(null); const [remark, setRemark] = useState(""); const office = profile.role as Office;
  const filtered = useMemo(() => items.filter(item => `${item.form.fullName} ${item.form.program}`.toLowerCase().includes(query.toLowerCase()) && (!status || (office === "cashier" ? item.payment.status : item.offices[office]) === status)), [items, query, status, office]);
  const act = async (decision: "approve" | "return") => { if (!selected) return; let next = structuredClone(selected); const label = roleLabel(profile.role); if (office === "cashier") next.payment = decision === "approve" ? { ...next.payment, status: "confirmed", receipt: `INS-${new Date().getFullYear()}-${Math.floor(Math.random()*90000+10000)}` } : { ...next.payment, status: "rejected" }; else if (office === "ict") next.idStatus = decision === "approve" ? "ready" : "scheduled"; else next.offices[office] = decision === "approve" ? "cleared" : "returned"; if (profile.role === "registrar" && decision === "approve") next.subjects = next.subjects.length ? next.subjects : sampleSubjects; next.remarks[office] = remark; next = addEvent(next, `${label}: ${decision === "approve" ? "approved / cleared" : "returned for correction"}${remark ? ` — ${remark}` : ""}`); await persist(next, decision); setSelected(null); setRemark(""); };
  const release = async () => { if (!selected) return; const ready = selected.payment.status === "confirmed" && (["osas","guidance","medical","scholarship"] as Office[]).every(o => selected.offices[o] === "cleared") && ["ready","completed"].includes(selected.idStatus) && selected.subjects.length; if (!ready) return alert("Payment, support clearances, assessment, ID processing, and assigned subjects must be complete."); let next = structuredClone(selected); next.status = "confirmed"; next.studentNumber ||= `${new Date().getFullYear()}-${String(Math.floor(Math.random()*90000+10000))}`; next.offices.registrar = "cleared"; next = addEvent(next, "Registrar released the official Enrollment Form"); await persist(next, "release"); setSelected(null); };
  return <><div className="page-head"><div><p className="eyebrow">ROLE-PROTECTED WORKSPACE</p><h1>{roleLabel(profile.role)} processing queue</h1><p>Review submitted records and leave a traceable decision.</p></div><div className="summary-pill"><strong>{filtered.length}</strong><span>records</span></div></div><div className="toolbar"><label><Search/><input placeholder="Search student or program" value={query} onChange={e => setQuery(e.target.value)}/></label><select value={status} onChange={e => setStatus(e.target.value)}><option value="">All statuses</option>{["submitted","under_review","returned","cleared","confirmed","rejected"].map(v => <option key={v} value={v}>{stateLabel(v)}</option>)}</select></div><section className="table-card"><div className="table-head"><span>Student</span><span>Program</span><span>Campus</span><span>Status</span><span>Updated</span></div>{filtered.map(item => <button className="table-row" key={item.id} onClick={() => setSelected(item)}><span><strong>{item.form.fullName || "Unnamed student"}</strong><small>{item.studentNumber || "Not yet assigned"}</small></span><span>{item.form.program}</span><span>{item.form.campus}</span><Status value={office === "cashier" ? item.payment.status : office === "ict" ? item.idStatus : item.offices[office]}/><span>{new Date(item.updatedAt).toLocaleDateString()}</span></button>)}{!filtered.length && <Empty title="Queue is clear" text="No records match the current filters."/>}</section>
    {selected && <div className="drawer-backdrop" onMouseDown={() => setSelected(null)}><aside className="drawer" onMouseDown={e => e.stopPropagation()}><button className="icon close" onClick={() => setSelected(null)}><X/></button><p className="eyebrow">STUDENT RECORD</p><h2>{selected.form.fullName}</h2><p>{selected.form.program} · {selected.form.studentType} · {selected.form.campus}</p><div className="detail-grid"><Stat value={selected.studentNumber || "Pending"} label="Student number"/><Stat value={stateLabel(selected.payment.status)} label="Payment"/><Stat value={`${selected.subjects.length}`} label="Assigned subjects"/><Stat value={stateLabel(selected.status)} label="Enrollment"/></div>{profile.role === "medical" ? <Alert tone="info">Only Medical Services and the student can access medical documents.</Alert> : <div className="document-summary"><h3>Submitted documents</h3>{Object.keys(selected.documents).map(name => <span key={name}><FileText/>{name}</span>)}</div>}{profile.role === "registrar" && <button className="secondary full" onClick={() => setSelected({ ...selected, subjects: sampleSubjects })}>Assign recommended subject load</button>}<Field label="Staff remarks"><textarea value={remark} onChange={e => setRemark(e.target.value)} placeholder="Required when returning a record"/></Field><div className="drawer-actions"><button className="danger" disabled={!remark.trim()} onClick={() => act("return")}>Return for correction</button><button className="primary" onClick={() => act("approve")}>Approve / clear</button></div>{profile.role === "registrar" && <button className="release" onClick={release}>Release enrollment form</button>}<h3>Activity history</h3><Timeline events={selected.events}/></aside></div>}</>;
}

function AdminPortal({ items }: { items: Enrollment[] }) {
  const [programs, setPrograms] = useState<string[]>([]); const [name, setName] = useState("");
  const reload = () => getPrograms().then(setPrograms); useEffect(() => { void reload(); }, []);
  const add = async () => { const value = name.trim(); if (!value || programs.includes(value)) return; if (isSupabaseConfigured) await addProgram(value); else localStorage.setItem("chmsu-programs", JSON.stringify([...programs, value])); setName(""); await reload(); };
  const deactivate = async (program: string) => { if (isSupabaseConfigured) await deactivateProgram(program); else localStorage.setItem("chmsu-programs", JSON.stringify(programs.filter(v => v !== program))); await reload(); };
  return <><div className="page-head"><div><p className="eyebrow">SYSTEM ADMINISTRATION</p><h1>Academic setup</h1><p>Manage reference data without changing historical enrollment records.</p></div></div><div className="stats-row"><Stat value={items.length} label="Enrollment records"/><Stat value={programs.length} label="Active programs"/><Stat value="9" label="System roles"/></div><section className="card"><div className="section-title"><div><h2>Programs</h2><p>Programs remain referenced by completed records when deactivated.</p></div></div><form className="inline-form" onSubmit={e => { e.preventDefault(); void add(); }}><input placeholder="New program name" value={name} onChange={e => setName(e.target.value)}/><button className="primary">Add program</button></form><div className="manage-list">{programs.map(program => <div key={program}><BookOpen/><strong>{program}</strong><Status value="active"/><button className="link" onClick={() => void deactivate(program)}>Deactivate</button></div>)}</div></section></>;
}

function Documents({ item }: { item: Enrollment }) { return <section className="card"><h2>My documents</h2><div className="manage-list">{Object.entries(item.documents).map(([name,path]) => <div key={name}><FileText/><span><strong>{name}</strong><small>{path}</small></span><Status value="uploaded"/></div>)}{!Object.keys(item.documents).length && <Empty title="No files uploaded" text="Documents added during enrollment will appear here."/>}</div></section>; }
function Timeline({ events }: { events: Enrollment["events"] }) { return <div className="timeline">{events.map((event,index) => <div key={`${event.at}-${index}`}><i/><span><strong>{event.text}</strong><small>{new Date(event.at).toLocaleString()}</small></span></div>)}</div>; }
function Field({ label, children }: { label: string; children: ReactNode }) { return <label className="field"><span>{label}</span>{children}</label>; }
function Status({ value }: { value: string }) { return <span className={`status ${value}`}>{stateLabel(value)}</span>; }
function Stat({ value, label }: { value: string | number; label: string }) { return <div className="stat"><strong>{value}</strong><span>{label}</span></div>; }
function Alert({ tone, children }: { tone: "error" | "success" | "info"; children: ReactNode }) { return <div className={`alert ${tone}`}>{children}</div>; }
function Nav({ icon, label }: { icon: ReactNode; label: string }) { return <button className="nav active">{icon}<span>{label}</span></button>; }
function Empty({ title, text }: { title: string; text: string }) { return <div className="empty"><ClipboardList/><h3>{title}</h3><p>{text}</p></div>; }
function Centered({ children }: { children: ReactNode }) { return <div className="centered">{children}</div>; }
